// Code generated by ./cmd/generate-zerolog; DO NOT EDIT.

package diag

import "fmt"

// MsgData fields functions

func (d *zerologLogData) Str(key string, value string) MsgData {
	return &zerologLogData{Event: d.Event.Str(key, value)}
}

func (d *zerologLogData) Strs(key string, value []string) MsgData {
	return &zerologLogData{Event: d.Event.Strs(key, value)}
}

func (d *zerologLogData) Stringer(key string, value fmt.Stringer) MsgData {
	return &zerologLogData{Event: d.Event.Stringer(key, value)}
}

func (d *zerologLogData) Bytes(key string, value []byte) MsgData {
	return &zerologLogData{Event: d.Event.Bytes(key, value)}
}

func (d *zerologLogData) Hex(key string, value []byte) MsgData {
	return &zerologLogData{Event: d.Event.Hex(key, value)}
}
